@root = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJpYXQiOjE2NDY4MjIwMzQsImV4cCI6MTY0NjgyNTYzNH0.JmnPmqAFoVS-qFkYqLDvQALFpYGhU-1EqezBsKuLWY8

### Root
GET {{root}}
Authorization: Bearer {{token}}

### Signup
POST {{root}}/signup
Content-Type: application/json

{
  "email": "a@a",
  "password": "a",
  "username": "a"
}

### Login
POST {{root}}/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Delete User
DELETE {{root}}/users
Authorization: Bearer {{token}}

### Get One User
GET {{root}}/users/1
Authorization: Bearer {{token}}

### Create Post
POST {{root}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Rick & Morty are cooool!"
}

### Get All Posts
GET {{root}}/posts
Authorization: Bearer {{token}}