@root = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyLCJpYXQiOjE2NDY4MTAwNTAsImV4cCI6MTY0NjgxMzY1MH0.g-2Qej9mTNEgGlrUHE68HwNlOFPKFizd09eJfiRWZOc

### Root
GET {{root}}

### Signup
POST {{root}}/signup
Content-Type: application/json

{
  "email": "a@a",
  "password": "a",
  "username": "a"
}

### Login
POST {{root}}/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Delete User
DELETE {{root}}/users
Authorization: Bearer {{token}}

### Create Post
POST {{root}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Rick & Morty are cooool!"
}