@root = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJpYXQiOjE2NDY3MzY3MzAsImV4cCI6MTY0NjczNjc2MH0.4MaSoUjbnB64OMzysHqLhn-poSYa-1oB0KHe4jROXzA

### Root
GET {{root}}

### Signup
POST {{root}}/signup
Content-Type: application/json

{
  "email": "a@a",
  "password": "a",
  "username": "a"
}

### Login
POST {{root}}/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Delete User
DELETE {{root}}/users
Authorization: Bearer {{token}}